// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrate/introspect usam a conexão direta (sem pgbouncer) — necessário
  // para DDL e para o shadow database do `migrate dev`. O runtime da app
  // (src/lib/prisma.ts) usa DATABASE_URL (pooled) via @prisma/adapter-pg.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
